### ISSUE TITLE
Editor is not showing?

### ISSUE THREAD

**Issue by josvenes** [miamarti/ng.ckeditor#18]
The editor is not showing.
I copied everything from a working fiddle
Filelinks are good.
What could be the reason?

[script.txt](https://github.com/miamarti/ng.ckeditor/files/1011957/script.txt)

browser log>>>>>
TypeError: Cannot read property 'destroy' of undefined
    at a.destroy (voorbeelden/editor/ckeditor/ckeditor.js:243:333)
    at Object.fn (voorbeelden/editor/ckeditor/angularjs/ng-ckeditor.js:113:28)
    at l.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:123:468)
    at l.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:126:417)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:17:448
    at Object.e [as invoke] (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:37:96)
    at d (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:17:369)
    at oc (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:18:153)
    at Dd (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:16:483)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:251:480 (21:35:35:472 | error, null)

  at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.1/angular.min.js:103

**Comment by miamarti** [comment]
Hi @josvenes,
You need to have an Angular project installed and configured.
I recommend that you use the code generator http://yeoman.io/generators/

[]s

**Comment by josvenes** [comment]
The problem was a bad config.js for the ckeditor

//Jos

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Miller Augusto<mailto:notifications@github.com>
Verzonden: donderdag 18 mei 2017 22:27
Aan: miamarti/ng.ckeditor<mailto:ng.ckeditor@noreply.github.com>
CC: josvenes<mailto:venes@live.nl>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [miamarti/ng.ckeditor] Editor is not showing? (#18)


Hi @josvenes<https://github.com/josvenes>,
You need to have an Angular project installed and configured.
I recommend that you use the code generator http://yeoman.io/generators/

[]s
